version: '3'

services:
  web:
    image: jaroslaw243/tiibd:latest
    command: bash -c "gunicorn waste_storage.wsgi:application --bind web:8000"
    volumes:
      - static_volume:/usr/src/code/static
    networks:
      - front_network
    restart: always
    expose:
      - '8000'
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/code/static
    networks:
      - front_network
    restart: always
    ports:
      - 1410:80
    depends_on:
      - web

volumes:
  static_volume:

networks:
  front_network: