from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('add', views.add_form),
    path('view_week', views.view_db_waste_week),
    path('view_month', views.view_db_waste_month),
    path('view_quarter', views.view_db_waste_quarter),
    path('view_year', views.view_db_waste_year),
    path('view_all', views.view_db_waste_all),
    path('view_monthly_report', views.view_db_monthly_report),
    path('view_search', views.search_form),
    path('search_by_date', views.view_by_date_search),
    path('search_by_name', views.view_by_name_search),
    path('bck_rad_week', views.bck_rad_week),
    path('bck_rad_month', views.bck_rad_month),
    path('bck_rad_quarter', views.bck_rad_quarter),
    path('bck_rad_year', views.bck_rad_year),
    path('bck_rad_all', views.bck_rad_all),
    path('add_to_db', views.add_form),
    path('remove', views.remove_waste),
    path('add_to_db_submit', views.add_to_db_submit),
    path('remove_submit', views.remove_waste_submit),
    path('gear', views.gear),
    path('calibrate_gear', views.calibrate),
    path('calibrate_gear_submit', views.calibrate_submit),
    path('log_out_submit', views.log_out),
    path('add_new_mes', views.add_new_mes_form),
    path('add_new_bg_mes', views.add_new_bg_mes_form),
    path('add_mes_submit', views.add_mes_submit),
    path('add_bq_mes_submit', views.add_bg_mes_submit),
    path('print', views.print_choice),
    path('print_submit', views.print_waste_card),
    path('move_waste', views.move_waste),
    path('move_waste_submit', views.move_waste_submit),
    path('return_waste', views.return_waste),
    path('return_waste_submit', views.return_waste_submit),
    path('comment', views.comment),
    path('comment_submit', views.comment_submit),
    path('change_tank_state', views.change_tank_state),
    path('change_tank_state_submit', views.change_tank_state_submit),
    path('change_tank_fill', views.change_tank_fill),
    path('change_tank_fill_submit', views.change_tank_fill_submit),
    path('tank_mes', views.tank_mes),
    path('tank_mes_submit', views.tank_mes_submit),
    path('view_tanks_month', views.view_tanks_month),
    path('view_tanks_all', views.view_tanks_all)
]
